@startuml
' https://www.plantuml.com/plantuml/uml/

hide empty members

class LcdMenu {
    +virtual bool process(char c)
    #virtual bool up()
    #virtual bool down()
    #virtual bool enter()
    #virtual bool back()
}

struct MenuItem::Context {
    LcdMenu* menu;
    DisplayInterface* display;
    const unsigned char command;
}

class MenuItem {
    #virtual bool process(Context context)
}

class ItemCommand {
    #bool process(Context context) override
    #bool enter(Context context)
}

class ItemList {
    #bool process(Context context) override
    #bool up(Context context)
    #bool down(Context context)
    #bool enter(Context context)
    #bool back(Context context)
}

class ItemInput {
    #bool process(Context context) override
    #bool up(Context context)
    #bool down(Context context)
    #bool enter(Context context)
    #bool back(Context context)
    #bool left(Context context)
    #bool right(Context context)
    #bool backspace(Context context)
    #bool typeChar(Context context)
    #bool clear(Context context)
}

LcdMenu::process -r-> MenuItem::process
ItemCommand -u-|> MenuItem
ItemList -u-|> MenuItem
ItemInput -u-|> MenuItem
@enduml