name: Notes

on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to generate release notes for"
        required: true

jobs:
  publish:
    name: Prepare Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install @actions/github
        run: npm install @actions/github

      - name: Generate Release Notes
        id: generate_release_notes
        uses: actions/github-script@v6
        env:
          CURRENT_TAG: ${{ github.event.inputs.part_to_increment || '5.0.0' }}
        with:
          script: |
            const generateReleaseNotes = require('.scripts/release_notes.js');
            const releaseNotes = await generateReleaseNotes(github, context);
            core.setOutput('release_notes', releaseNotes);

      - name: Comment on PR with Release Notes
        if: success()
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const releaseNotes = `## Release Notes\n\n${{ steps.generate_release_notes.outputs.release_notes }}`;
            const prNumber = context.payload.pull_request.number;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: releaseNotes
            });
